### ISSUE TITLE
Application basic setup

### ISSUE THREAD

**Issue by OpenTechConsult** [OpenTechConsult/memories#3]
We are going to create the memories application structure. The project consists of two sub-projects: client and server. The client is a React application and the server is a simple Node.js backend API.

**Tasks**

- [x] inside _memories_ root folder create two subfolders called _client_ and _server_
- [x] change directory into the client directory and initialize a react application by typing `yarn create react-app ./` to generate a react application
- [x] hop into the server directory and create the server.js file which will serve as the entry point to the node.js backend API application.
- [x] install the application dependencies to be used in the backend API. The dependencies are: body parser, cors, express, mongoose nodemon
- [x] modify the _package.json_ by setting the `type` property to module to enable us to use `import` statement instead of `require()` function. 
- [x] also, always in the package.json file, add a `start` script in the scripts object
- [x] in server.js let's write the code to setup a node.js web server
- [x] go back to client folder and install additional dependencies to be used by the react application
